const USER_LOGGED = "USER_LOGGED";
const PET_REGISTER = "PET_REGISTER";
const CLOSE_BANNER = "CLOSE_BANNER";
const USER_UNLOGGED = "USER_UNLOGGED";

export { USER_LOGGED, PET_REGISTER, CLOSE_BANNER, USER_UNLOGGED };